// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBol2BZRIPCB-Bn1ynpMMtaIVDNDfPJMdU',
    appId: '1:1082810759185:web:63516b2dea883086f099b0',
    messagingSenderId: '1082810759185',
    projectId: 'movies-app-6f812',
    authDomain: 'movies-app-6f812.firebaseapp.com',
    storageBucket: 'movies-app-6f812.firebasestorage.app',
    measurementId: 'G-CDPSF1NXB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhOLiZK87a9AyLwKCZIJE-X32tigV1Cag',
    appId: '1:1082810759185:android:3483be03c0fc242ff099b0',
    messagingSenderId: '1082810759185',
    projectId: 'movies-app-6f812',
    storageBucket: 'movies-app-6f812.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgArMyWtH96BWVg6H3TBPfdA5YwCqZSMQ',
    appId: '1:1082810759185:ios:000aba504d2f784ff099b0',
    messagingSenderId: '1082810759185',
    projectId: 'movies-app-6f812',
    storageBucket: 'movies-app-6f812.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgArMyWtH96BWVg6H3TBPfdA5YwCqZSMQ',
    appId: '1:1082810759185:ios:000aba504d2f784ff099b0',
    messagingSenderId: '1082810759185',
    projectId: 'movies-app-6f812',
    storageBucket: 'movies-app-6f812.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBol2BZRIPCB-Bn1ynpMMtaIVDNDfPJMdU',
    appId: '1:1082810759185:web:92fcc01804859a3ef099b0',
    messagingSenderId: '1082810759185',
    projectId: 'movies-app-6f812',
    authDomain: 'movies-app-6f812.firebaseapp.com',
    storageBucket: 'movies-app-6f812.firebasestorage.app',
    measurementId: 'G-DGG8QZCMR5',
  );
}
